# define a default docker image for all jobs
image: node:8.10

stages:
    - install # install all npm dependencies
    - test    # execute unit tests

npmInstall:
    stage: install
    script:
        - npm install --production
    # artifacts describe the result of the stage
    # that can be used in consecutive stages
    artifacts:
        untracked: true

unittesting:
    stage: test
    # use the artifcats of the 'npmInstall' job
    dependencies:
        - npmInstall
    variables:
        API_KEY: $API_KEY
    script:
        # install dev-dependency mocha
        - npm install
        - npm test